import { Poppins } from 'next/font/google';
import { Roboto } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin-ext'],
  weight: ['400', '600', '700'], 
  variable: '--font-poppins', 
});

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',   
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className='scroll-smooth' suppressHydrationWarning>
      <body className={`${poppins.variable}, ${roboto.variable} antialiased 
      leading-6 overflow-x-hidden scroll-sm bg-white text-black dark:bg-darkTheme dark:text-white ` }>{children}</body>
    </html>
  );
}